"""add route_geozones

Revision ID: 68f3d316db7e
Revises: fe4a4f6ef87a
Create Date: 2026-07-24 21:12:49.313073
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68f3d316db7e'
down_revision: Union[str, Sequence[str], None] = 'fe4a4f6ef87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_geozones',
    sa.Column('route_geozones_id', sa.String(length=36), nullable=False),
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_fraction', sa.Float(), nullable=False),
    sa.Column('end_fraction', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routes_id'], ['routes.routes_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_geozones_id')
    )
    op.create_index(op.f('ix_route_geozones_routes_id'), 'route_geozones', ['routes_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_geozones_routes_id'), table_name='route_geozones')
    op.drop_table('route_geozones')
    # ### end Alembic commands ###
