"""create pipeline tables

Revision ID: 6cfc82929998
Revises: 
Create Date: 2026-06-23 13:16:55.620250
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '6cfc82929998'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('pipeline_runs_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('source_object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('source_content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('frame_stride', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pipeline_runs_id'),
    sa.UniqueConstraint('source_object_key')
    )
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_runs_queue', 'pipeline_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_worker_id'), 'pipeline_runs', ['worker_id'], unique=False)
    op.create_table('pipeline_artifacts',
    sa.Column('pipeline_artifacts_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_artifacts_id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('pipeline_runs_id', 'artifact_type', 'object_key', name='uq_pipeline_artifact_run_type_key')
    )
    op.create_index(op.f('ix_pipeline_artifacts_artifact_type'), 'pipeline_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), 'pipeline_artifacts', ['pipeline_runs_id'], unique=False)
    op.create_table('pipeline_run_events',
    sa.Column('pipeline_run_events_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_run_events_id')
    )
    op.create_index(op.f('ix_pipeline_run_events_created_at'), 'pipeline_run_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), 'pipeline_run_events', ['pipeline_runs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), table_name='pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_run_events_created_at'), table_name='pipeline_run_events')
    op.drop_table('pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_artifact_type'), table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_worker_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_queue', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
