"""init

Revision ID: 9c489a3d8a73
Revises: 
Create Date: 2026-07-16 08:53:06.628231
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c489a3d8a73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('roads_geojson_path', sa.String(length=512), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cities_id')
    )
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('routes',
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_label', sa.String(length=64), nullable=True),
    sa.Column('color_hex', sa.String(length=16), nullable=True),
    sa.Column('geojson_path', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.cities_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routes_id'),
    sa.UniqueConstraint('cities_id', 'slug', name='uq_routes_city_slug')
    )
    op.create_index(op.f('ix_routes_cities_id'), 'routes', ['cities_id'], unique=False)
    op.create_table('route_batches',
    sa.Column('route_batches_id', sa.String(length=36), nullable=False),
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routes_id'], ['routes.routes_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_batches_id'),
    sa.UniqueConstraint('routes_id', 'sequence_number', name='uq_route_batches_route_sequence')
    )
    op.create_index(op.f('ix_route_batches_created_at'), 'route_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_batches_routes_id'), 'route_batches', ['routes_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('source_object_key', sa.String(length=1024), nullable=False),
    sa.Column('source_content_type', sa.String(length=255), nullable=True),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('route_batches_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('frame_stride', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_batches_id'], ['route_batches.route_batches_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pipeline_runs_id'),
    sa.UniqueConstraint('source_object_key')
    )
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_runs_queue', 'pipeline_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_route_batches_id'), 'pipeline_runs', ['route_batches_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_worker_id'), 'pipeline_runs', ['worker_id'], unique=False)
    op.create_table('pipeline_artifacts',
    sa.Column('pipeline_artifacts_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_artifacts_id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('pipeline_runs_id', 'artifact_type', 'object_key', name='uq_pipeline_artifact_run_type_key')
    )
    op.create_index(op.f('ix_pipeline_artifacts_artifact_type'), 'pipeline_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), 'pipeline_artifacts', ['pipeline_runs_id'], unique=False)
    op.create_table('pipeline_run_events',
    sa.Column('pipeline_run_events_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_run_events_id')
    )
    op.create_index(op.f('ix_pipeline_run_events_created_at'), 'pipeline_run_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), 'pipeline_run_events', ['pipeline_runs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), table_name='pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_run_events_created_at'), table_name='pipeline_run_events')
    op.drop_table('pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_artifact_type'), table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_worker_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_route_batches_id'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_queue', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_route_batches_routes_id'), table_name='route_batches')
    op.drop_index(op.f('ix_route_batches_created_at'), table_name='route_batches')
    op.drop_table('route_batches')
    op.drop_index(op.f('ix_routes_cities_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
