"""Схема целиком: все одиннадцать таблиц в текущем виде.

Это схлопнутая история. До 28.07.2026 схема набиралась восемью миграциями —
init, два сида городов, сид маршрутов, геозоны, каталог, описание геозоны,
переезд геометрии в БД, — и половина из них правила то, что добавила предыдущая:
колонки `geojson_path` / `roads_geojson_path` появились и были удалены, так и не
дожив до продакшена.

Схлопнуто по действующему решению: база пока dev, переносить в миграции нечего,
поэтому одна честная миграция вместо восьми со следами отменённых замыслов.
Правило перестаёт действовать в день, когда появится живая база с данными,
которые нельзя потерять, — с этого дня история только дописывается.

Справочные данные (города и маршруты) сюда не входят: они отдельной миграцией
`0002_seed`, потому что схема и содержимое живут разной жизнью — схему заменит
следующая миграция, а сиды однажды заменит админка.

Revision ID: 0001_schema
Revises:
Create Date: 2026-07-28
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('roads_geometry', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('bounds_min_latitude', sa.Float(), nullable=True),
    sa.Column('bounds_max_latitude', sa.Float(), nullable=True),
    sa.Column('bounds_min_longitude', sa.Float(), nullable=True),
    sa.Column('bounds_max_longitude', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cities_id')
    )
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('users_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.create_table('catalog_imports',
    sa.Column('catalog_imports_id', sa.String(length=36), nullable=False),
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('file_names', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('points_total', sa.Integer(), nullable=False),
    sa.Column('files_rejected', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_users_id', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.cities_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_users_id'], ['users.users_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('catalog_imports_id'),
    sa.UniqueConstraint('cities_id', 'revision', name='uq_catalog_imports_city_revision')
    )
    op.create_index('ix_catalog_imports_city_current', 'catalog_imports', ['cities_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_catalog_imports_created_at'), 'catalog_imports', ['created_at'], unique=False)
    op.create_index(op.f('ix_catalog_imports_status'), 'catalog_imports', ['status'], unique=False)
    op.create_index(op.f('ix_catalog_imports_uploaded_by_users_id'), 'catalog_imports', ['uploaded_by_users_id'], unique=False)
    op.create_table('routes',
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_label', sa.String(length=64), nullable=True),
    sa.Column('color_hex', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.cities_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routes_id'),
    sa.UniqueConstraint('cities_id', 'slug', name='uq_routes_city_slug')
    )
    op.create_index(op.f('ix_routes_cities_id'), 'routes', ['cities_id'], unique=False)
    op.create_table('ad_structures',
    sa.Column('ad_structures_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_imports_id', sa.String(length=36), nullable=False),
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('surfaces_count', sa.Integer(), nullable=False),
    sa.Column('source_rows', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_imports_id'], ['catalog_imports.catalog_imports_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cities_id'], ['cities.cities_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ad_structures_id')
    )
    op.create_index(op.f('ix_ad_structures_catalog_imports_id'), 'ad_structures', ['catalog_imports_id'], unique=False)
    op.create_index(op.f('ix_ad_structures_cities_id'), 'ad_structures', ['cities_id'], unique=False)
    op.create_table('assignments',
    sa.Column('assignments_id', sa.String(length=36), nullable=False),
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_users_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_users_id'], ['users.users_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routes_id'], ['routes.routes_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignments_id'),
    sa.UniqueConstraint('routes_id', 'sequence_number', name='uq_assignments_route_sequence')
    )
    op.create_index(op.f('ix_assignments_author_users_id'), 'assignments', ['author_users_id'], unique=False)
    op.create_index(op.f('ix_assignments_created_at'), 'assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignments_routes_id'), 'assignments', ['routes_id'], unique=False)
    op.create_table('route_geozones',
    sa.Column('route_geozones_id', sa.String(length=36), nullable=False),
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('start_fraction', sa.Float(), nullable=False),
    sa.Column('end_fraction', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routes_id'], ['routes.routes_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_geozones_id')
    )
    op.create_index(op.f('ix_route_geozones_routes_id'), 'route_geozones', ['routes_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('source_object_key', sa.String(length=1024), nullable=False),
    sa.Column('source_content_type', sa.String(length=255), nullable=True),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('assignments_id', sa.String(length=36), nullable=False),
    sa.Column('shot_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by_users_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('frame_stride', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignments_id'], ['assignments.assignments_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_users_id'], ['users.users_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pipeline_runs_id'),
    sa.UniqueConstraint('source_object_key')
    )
    op.create_index(op.f('ix_pipeline_runs_assignments_id'), 'pipeline_runs', ['assignments_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_uploaded_by_users_id'), 'pipeline_runs', ['uploaded_by_users_id'], unique=False)
    op.create_index('ix_pipeline_runs_queue', 'pipeline_runs', ['status', 'created_at'], unique=False)
    op.create_table('dwh_video_metrics',
    sa.Column('dwh_video_metrics_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('cities_id', sa.String(length=36), nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('routes_id', sa.String(length=36), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('assignments_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('sum_visibility_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dwh_video_metrics_id')
    )
    op.create_index('ix_dwh_video_metrics_run_revision', 'dwh_video_metrics', ['pipeline_runs_id', 'revision'], unique=False)
    op.create_table('pipeline_artifacts',
    sa.Column('pipeline_artifacts_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_artifacts_id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('pipeline_runs_id', 'artifact_type', 'object_key', name='uq_pipeline_artifact_run_type_key')
    )
    op.create_index(op.f('ix_pipeline_artifacts_artifact_type'), 'pipeline_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), 'pipeline_artifacts', ['pipeline_runs_id'], unique=False)
    op.create_table('pipeline_run_events',
    sa.Column('pipeline_run_events_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_runs_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_runs_id'], ['pipeline_runs.pipeline_runs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_run_events_id')
    )
    op.create_index(op.f('ix_pipeline_run_events_created_at'), 'pipeline_run_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), 'pipeline_run_events', ['pipeline_runs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_events_pipeline_runs_id'), table_name='pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_run_events_created_at'), table_name='pipeline_run_events')
    op.drop_table('pipeline_run_events')
    op.drop_index(op.f('ix_pipeline_artifacts_pipeline_runs_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_artifact_type'), table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    op.drop_index('ix_dwh_video_metrics_run_revision', table_name='dwh_video_metrics')
    op.drop_table('dwh_video_metrics')
    op.drop_index('ix_pipeline_runs_queue', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_uploaded_by_users_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_assignments_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_route_geozones_routes_id'), table_name='route_geozones')
    op.drop_table('route_geozones')
    op.drop_index(op.f('ix_assignments_routes_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_author_users_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_ad_structures_cities_id'), table_name='ad_structures')
    op.drop_index(op.f('ix_ad_structures_catalog_imports_id'), table_name='ad_structures')
    op.drop_table('ad_structures')
    op.drop_index(op.f('ix_routes_cities_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_catalog_imports_uploaded_by_users_id'), table_name='catalog_imports')
    op.drop_index(op.f('ix_catalog_imports_status'), table_name='catalog_imports')
    op.drop_index(op.f('ix_catalog_imports_created_at'), table_name='catalog_imports')
    op.drop_index('ix_catalog_imports_city_current', table_name='catalog_imports')
    op.drop_table('catalog_imports')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
